export const CREATE_NEW_OBJECT = "CREATE_NEW_OBJECT"
export const CALL_MODEL_WINDOW = 'CALL_MODEL_WINDOW'
export const CLOSE_WINDOW = 'CLOSE_WINDOW'
export const OPEN_OBJECT = 'OPEN_OBJECT'
export const OPEN_INDEX = 'OPEN_INDEX'
export const CREATE_ACTIV_INDEX_VEU = 'CREATE_ACTIV_INDEX_VEU'

export const ADD_BOTTOM_SUPPORTING = 'ADD_BOTTOM_SUPPORTING'
export const ADD_BOTTOM_TEMPLATE = 'ADD_BOTTOM_TEMPLATE'
export const ADD_BOTTOM_ANCHOR = 'ADD_BOTTOM_ANCHOR'
export const ADD_BOTTOM_UZER = 'ADD_BOTTOM_UZER'
export const ADD_BOTTOM_DATE = 'ADD_BOTTOM_DATE'

export const ADD_START_TEMPLATE = 'ADD_START_TEMPLATE'
export const ADD_START_ANCHOR = 'ADD_START_ANCHOR'
export const ADD_START_UZER = 'ADD_START_UZER'
export const ADD_START_DATE = 'ADD_START_DATE'

export const ADD_CONCRETE_TEMPLATE = 'ADD_CONCRETE_TEMPLATE'
export const ADD_CONCRETE_ANCHOR = 'ADD_CONCRETE_ANCHOR'
export const ADD_CONCRETE_UZER = 'ADD_CONCRETE_UZER'
export const ADD_CONCRETE_DATE = 'ADD_CONCRETE_DATE'
