export const CREATE_NEW_OBJECT = "CREATE_NEW_OBJECT"
export const CALL_MODEL_WINDOW = 'CALL_MODEL_WINDOW'
export const CLOSE_WINDOW = 'CLOSE_WINDOW'
export const OPEN_OBJECT = 'OPEN_OBJECT'
export const OPEN_INDEX = 'OPEN_INDEX'
export const CREATE_ACTIV_INDEX_VEU = 'CREATE_ACTIV_INDEX_VEU'

export const SAVE_TO_STORE_BOTTOM = 'SAVE_TO_STORE_BOTTOM'
export const SAVE_TO_STORE_START = 'SAVE_TO_STORE_START'
export const SAVE_TO_STORE_CONCRETE = 'SAVE_TO_STORE_CONCRETE'

export const SAVE_X_Y_H_TO_STORE = 'SAVE_X_Y_H_TO_STORE'
export const INIT_STATE = 'INIT_STATE'
export const RESET_STATE = 'RESET_STATE'
export const KEY_BASE_TO_STORE ='KEY_BASE_TO_STORE'
export const ADD_NEW_NAME_OBJECT = 'ADD_NEW_NAME_OBJECT'

export const START_INIT_TO_STORE = 'START_INIT_TO_STORE'
export const FINISH_INIT_TO_STORE ='FINISH_INIT_TO_STORE'
export const START_CREATE_NEW_OBJECT = 'START_CREATE_NEW_OBJECT'
export const BTN_OBJECT_DISABLED_OF = 'BTN_OBJECT_DISABLED_OF'

export const START_SAVE_TO_BASE_BOTTOM = 'START_SAVE_TO_BASE_BOTTOM'
export const FINISH_SAVE_TO_BASE = 'FINISH_SAVE_TO_BASE'
export const START_SAVE_TO_BASE_START = 'START_SAVE_TO_BASE_START'
export const START_SAVE_TO_BASE_CONCRETE = 'START_SAVE_TO_BASE_CONCRETE'

export const START_SAVE_TO_BASE_XYH = 'START_SAVE_TO_BASE_XYH'

export const INPUT_OFFLINE = 'INPUT_OFFLINE'


